# config file to setup server
env: "local"
storage_path: "./storage/storage.db"
app_secret: "url-secret"
http_server:
  address: "localhost:8082"
  timeout: 4s
  iddle_timeout: 60s
  user: "myuser"
  password: "mypass"